os:
  - linux
  - osx
language: generic
sudo: required
dist: trusty
osx_image: xcode7.2
env:
  - SWIFT_VERSION=DEVELOPMENT-SNAPSHOT-2016-03-01-a
script:
  - swift build
  - swift test
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then xcodebuild -project Xcode/Date/Date.xcodeproj -scheme Date build test ; fi
  